### PR TITLE
ui: ctrl-w to close plugin window

### PR DESCRIPTION
**Pull request by jean-emmanuel**
This add the common keyboard shortcut for closing windows to ladspa plugins. It would be nice to have it for lv2 external ui's as well, but I'm not sure where and how to do it.

### CODE REVIEW

**Comment by Stazed** [comment]
Getting an implicit fall through warning from the previous:
> case FL_PUSH

Just add a break before the FL_KEYBOARD case.

I will see what can be done for LV2 custom. X11 embedded should be doable, showInterface and external UIs probably not.

**Comment by Stazed** [comment]
I went ahead and manually applied this one since I was already there.
You will need to rebase your fork.

**Comment by jean-emmanuel** [comment]
Thank you very much, and sorry for the lack of precision on my end, I forgot to enable debug build options and didn't see the warnings...

**Comment by jean-emmanuel** [comment]
X11's current binding for ctrl+w doesn't work with keyboard layouts other than qwerty, I guess we need to check the key symbol rather than the keycode.

**Pull request closed without merging**
